global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'python-flask-app'
    static_configs:
      - targets: ['host.docker.internal:5000']

# If running Prometheus on same machine and scraping localhost directly, change
# the target to 'localhost:5000'.
