global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'python-flask-app'
    static_configs:
      - targets: ['app:5000']
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']

# If running Prometheus on same machine and scraping localhost directly, change
# the target to 'localhost:5000'.
