global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'python-flask-app'
    static_configs:
      - targets: ['app:5000']
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
  - job_name: 'blackbox-probes'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://example.com
          - https://httpbin.org/status/200
          - https://github.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: __address__
        replacement: blackbox:9115
      - source_labels: [__param_target]
        target_label: instance

# If running Prometheus on same machine and scraping localhost directly, change
# the target to 'localhost:5000'.
